### ISSUE TITLE
Setting baud rate fails

### ISSUE THREAD

**Issue by badders** [badders/pyallsky#1]
Setting the baud rate fails with no sensible reason. The protocol specification seems to be correct, but even after performing the last step the new baud rate isn't locked in. Attempting to set the baud rate this way also causes the auto-discovery of the baud rate to fail, and future connections require it to be hard coded.

**Comment by RonanHiggins** [comment]
Hi Badders,
thanks for the work on putting this on github saved me some hassle. I had a look at your code and was able to fix the baud rate detection **init** function. 
On line 91 of allsky.py I changed:
     ser.write(checksum(COM_TEST))
to:
     ser.write(COM_TEST+checksum(COM_TEST))
this auto detects the baud rate and runs through to the image download.

**Comment by badders** [comment]
Thanks Ronan, i've applied your fix and pushed to master. I dont have the hardware with me to test but the fix looks good.
